name: Build PreIndexed Winget Repo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download WingetCreate CLI
        run: |
          Invoke-WebRequest -Uri "https://github.com/microsoft/winget-create/releases/latest/download/WingetCreate.exe" -OutFile "WingetCreate.exe"

      - name: Generate repo.sqlite
        run: |
          mkdir output
          ./WingetCreate.exe index --add-manifests ./manifests --output ./output/repo.sqlite

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
